apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: testandomeuclustereks
  region: eu-central-1

nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 1
    volumeSize: 20
  - name: ng-2
    instanceType: t2.medium
    desiredCapacity: 1
    volumeSize: 20

cloudWatch:
    clusterLogging:
        # enable specific types of cluster control plane logs
        enableTypes: ["audit", "authenticator", "controllerManager"]
        # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
        # supported special values: "*" and "all"
