Criar entrada no DNS
aws route53 create-hosted-zone --name "claro.renatodesouza.com.br." --caller-reference "external-dns-test-$(date +%s)"
#/hostedzone/Z05818183VZRTREGCODYP

Criar Iam Policy com json no console

Criar o OIDC provider
Observar o nome do cluster
eksctl utils associate-iam-oidc-provider --region=eu-central-1 --cluster=claroclustertest --approve

Criar imaserviceaccount com attach com o policy qye foi criado.
Observar o nome do cluster e use --override-existing-serviceaccounts caso já exista um serviceaccount
eksctl create iamserviceaccount --override-existing-serviceaccounts --name external-dns --namespace default --cluster claroclustertest --attach-policy-arn arn:aws:iam::681206901347:policy/EKS-CLaro --region=eu-central-1 --approve

Confirme o service com
k describe sa external-dns





apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    external-dns.alpha.kubernetes.io/hostname: nginx.eks.renatodesouza.com.br
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: nginx

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: http
